### ISSUE TITLE
webpack下报错，无法使用...

### ISSUE THREAD

**Issue by wuzhuzhu** [hahoocn/node-alidayu-sms#1]
```
SMSPoc/node_modules/tough-cookie/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
```

**Comment by wuzhuzhu** [comment]
`Cannot resolve module 'tls' in /Users/walter/ApolloProjects/SMSPoc/node_modules/forever-agent`

`Cannot resolve module 'fs' in /Users/walter/ApolloProjects/SMSPoc/node_modules/request/lib`

...
说缺了一堆模块》。

**Comment by ihahoo** [comment]
这个主要是后端Node下使用的模块，你是要用webpack直接打包给前端吗？

因为短信的发送，依赖了淘宝的SDK，我稍微修改了一下的sdk是[node-taobao-topclient](https://github.com/hahoocn/node-taobao-topclient)
而这里面用到的异步request是Node服务器端运行的request模块，非浏览器端。

因为调用短信接口要提供参数appkey和appsecret，这个放前端是不安全的。一般都是封装到服务器端，再开发接口供自己使用。否则被盗用，就直接可以调用你的账户发送短信了。

如果一定要前端调用，我想，可能需要修改一下[node-taobao-topclient](https://github.com/hahoocn/node-taobao-topclient)中的异步调用部分的request，更换为fetch或superagent之类的
